const GroceryAPI = [
    {
        id:1,
        autoimage: "img/grocery.png",
        title: "Grocery",
        time:"20 min",
        info:"Free delivery with Instacart+",
    },
    {
        id:2,
        autoimage: "img/EBT.png",
        title: "Grocery",
        time:"20 min",
        info:"Free delivery with Instacart+",
    },
    {
        id:3,
        autoimage: "img/alcohol.png",
        title: "Grocery",
        time:"20 min",
        info:"Free delivery with Instacart+",
    },
    {
        id:4,
        autoimage: "img/convenience.png",
        title: "Grocery",
        time:"20 min",
        info:"Free delivery with Instacart+",
    },
    {
        id:5,
        autoimage: "img/deals.png",
        title: "Grocery",
        time:"20 min",
        info:"Free delivery with Instacart+",
    },
    {
        id:6,
        autoimage: "img/wholesale.png",
        title: "Grocery",
        time:"20 min",
        info:"Free delivery with Instacart+",
    },
    {
        id:7,
        autoimage: "img/pickup.png",
        title: "Grocery",
        time:"20 min",
        info:"Free delivery with Instacart+",
    },
    {
        id:8,
        autoimage: "img/meals.png",
        title: "Grocery",
        time:"20 min",
        info:"Free delivery with Instacart+",
    },
    {
        id:9,
        autoimage: "img/beauty.png",
        title: "Grocery",
        time:"20 min",
        info:"Free delivery with Instacart+",
    },
    {
        id:10,
        autoimage: "img/electronics.png",
        title: "Grocery",
        time:"20 min",
        info:"Free delivery with Instacart+",
    },
    {
        id:11,
        autoimage: "img/gifts.png",
        title: "Grocery",
        time:"20 min",
        info:"Free delivery with Instacart+",
    },
    {
        id:12,
        autoimage: "img/pets.png",
        title: "Grocery",
        time:"20 min",
        info:"Free delivery with Instacart+",
    },
    {
        id:13,
        autoimage: "img/sports.png",
        title: "Grocery",
        time:"20 min",
        info:"Free delivery with Instacart+",
    },
    {
        id:14,
        autoimage: "img/community_cart.png",
        title: "Grocery",
        time:"20 min",
        info:"Free delivery with Instacart+",
    },
    {
        id:15,
        autoimage: "img/community_cart.png",
        title: "Grocery",
        time:"20 min",
        info:"Free delivery with Instacart+",
    },
    
   
]
export default GroceryAPI;