const GroceryAPI = [
    {
        id:1,
        autoimage: "img/grocery.png",
        title: "Grocery",
        time:"20 min",
        info:"Free delivery with Instacart+",
    },
    {
        id:2,
        autoimage: "img/EBT.png",
        title: "EBT",
        time:"25 min",
        info:"Free delivery on $35+ (first 3 orders)",
    },
    {
        id:3,
        autoimage: "img/alcohol.png",
        title: "Alcohol",
        time:"20 min",
        info:"Lower fees on $10+",
    },
    {
        id:4,
        autoimage: "img/convenience.png",
        title: "Convenience",
        time:"20 min",
        info:"Lower fees on $10+",
    },
    {
        id:5,
        autoimage: "img/deals.png",
        title: "Deals",
        time:"",
        info:"Updated daily",
    },
    {
        id:6,
        autoimage: "img/wholesale.png",
        title: "Wholesale",
        time:"30 min",
        info:"Free delivery with Instacart+",
    },
    {
        id:7,
        autoimage: "img/pickup.png",
        title: "Pickup",
        time:"Pickup ready in 55 min",
        info:"Lower fees than delivery",
    },
    {
        id:8,
        autoimage: "img/meals.png",
        title: "Ready Meals",
        time:"25 min",
        info:"Lower fees on $10+",
    },
    {
        id:9,
        autoimage: "img/beauty.png",
        title: "Beauty",
        time:"25 min",
        info:"Free delivery with Instacart+",
    },
    {
        id:10,
        autoimage: "img/electronics.png",
        title: "Electronics",
        time:"25 min",
        info:"Free delivery with Instacart+",
    },
    {
        id:11,
        autoimage: "img/gifts.png",
        title: "Gifts",
        time:"20 min",
        info:"Nationwide delivery",
    },
    {
        id:12,
        autoimage: "img/pets.png",
        title: "Pets",
        time:"20 min",
        info:"Free delivery with Instacart+",
    },
    {
        id:13,
        autoimage: "img/sports.png",
        title: "Sports Gear",
        time:"By 12:45pm",
        info:"Free delivery with Instacart+",
    },
    {
        id:14,
        autoimage: "img/rebit.png",
        title: "Deals",
        time:"Updated daily",
        info:"",
    },
    {
        id:15,
        autoimage: "img/community_cart.png",
        title: "Donate items",
        time:"",
        info:"Support a food bank",
    },
    
   
]
export default GroceryAPI;